version: "3.8"

services:
  ddclient:
    container_name: ddclient
    image: linuxserver/ddclient:v3.9.1-ls57
    restart: unless-stopped
    volumes:
      - ./ddclient/ddclient.conf:/config/ddclient.conf
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
