###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret: secret123
default_redirection_url: https://example.domain.com
totp:
  issuer: authelia.com

#duo_api:
#  hostname: api-123456789.domain.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: secret123

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: domain.com
      policy: bypass
    - domain: "*.domain.com"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: secret123
  expiration: 3600 # 1 hour
  inactivity: 600 # 10 minutes
  domain: domain.com # Should match whatever your root protected domain is

  redis:
    host: redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: secret123

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  # filesystem:
  #   filename: /config/notification.txt
  smtp:
    username: yourown@email.com
    # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    password: secret123
    sender: admin@domain.com
    host: smtp.gmail.com
    port: 587